variables:
  FlutterChannel: 'stable'
  FlutterVersion: 'latest'

  ProjectSlug: 'juraj.hamornik-outlook.com/Manapipes'
  ProjectDirectory: '$(Build.SourcesDirectory)'

  BuildNumber: '$(Build.BuildNumber)'
  BuildMessage: '$(Build.SourceVersionMessage)'
  BuildDirectory: '$(ProjectDirectory)/build/app/outputs/apk/release/app-release.apk'

jobs:
  - job: Build
    pool:
      vmImage: 'macOS-latest'
    steps:
      - task: FlutterInstall@0
        displayName: Setup flutter
        inputs:
          channel: '$(FlutterChannel)'
          version: '$(FlutterVersion)'

      - task: PowerShell@2
        displayName: Setup environment
        inputs:
          targetType: 'inline'
          script: |
            Write-Host "##vso[task.prependpath]$(JAVA_HOME_11_X64)"
            Write-Host "##vso[task.setvariable variable=JAVA_HOME;]$(JAVA_HOME_11_X64)"
            Write-Host "##vso[task.prependpath]$(FlutterToolPath)"
            Write-Host "##vso[task.prependpath]$(FlutterToolPath)/cache/dart-sdk/bin"

      - task: PowerShell@2
        displayName: Setup variables (beta)
        condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/')
        inputs:
          targetType: 'inline'
          script: |
            $buildName = "$(Build.SourceVersion)".SubString(0,7)
            $distributionGroup = "Internal"
            Write-Host "##vso[task.setvariable variable=BuildName;]$buildName"
            Write-Host "##vso[task.setvariable variable=DistributionGroup;]$distributionGroup"

      - task: PowerShell@2
        displayName: Setup variables (public)
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
        inputs:
          targetType: 'inline'
          script: |
            $buildName = "$(Build.SourceBranch)".SubString(11)
            $distributionGroup = "Internal"
            Write-Host "##vso[task.setvariable variable=BuildName;]$buildName"
            Write-Host "##vso[task.setvariable variable=DistributionGroup;]$distributionGroup"

      - task: CmdLine@2
        displayName: Run install
        inputs:
          script: 'flutter pub get'

      - task: FlutterBuild@0
        displayName: Run build
        inputs:
          target: 'apk'
          projectDirectory: '$(ProjectDirectory)'
          buildName: '$(BuildName)'
          buildNumber: '$(BuildNumber)'
