variables:
  FlutterChannel: 'stable'
  FlutterVersion: 'latest'

  ProjectSlug: '<APP_CENTER_USERNAME>/<APP_CENTER_APP>'
  ProjectDirectory: '$(Build.SourcesDirectory)'

  BuildNumber: '$(Build.BuildNumber)'
  BuildMessage: '$(Build.SourceVersionMessage)'
  BuildDirectory: '$(ProjectDirectory)/build/app/outputs/apk/release/app-release.apk'

trigger:
- master


pool:
  vmImage: 'macos-latest'

steps:
- task: FlutterInstall@0
  displayName: Setup flutter
  inputs:
    channel: 'stable'
    version: 'latest'


- task: Xcode@5
  inputs:
    actions: 'archive' 
    sdk: '$(sdk)'
    scheme: '$(scheme)'
    configuration: '$(configuration)'
    xcodeVersion: 'default' # Options: default, 10, 9, 8, specifyPath
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    
