variables:
  FlutterChannel: 'stable'
  FlutterVersion: 'latest'

  ProjectSlug: 'juraj.hamornik-outlook.com/Manapipes'
  ProjectDirectory: '$(Build.SourcesDirectory)'

  BuildNumber: ''
  BuildMessage: '$(Build.SourceVersionMessage)'
  BuildDirectoryIos: '$(ProjectDirectory)/build/ios/build/app.ipa'
  BuildDirectoryAndroid: '$(ProjectDirectory)/build/app/outputs/apk/release/app-release.apk'
  YOUR_TOKEN: '414d9c39086268a3a50dc01138f1c87da253e152'
  ipaApkName: app
jobs:
  - job: Build
    pool:
      vmImage: 'macOS-latest'
    steps:
      - task: FlutterInstall@0
        displayName: Setup flutter
        inputs:
          channel: '$(FlutterChannel)'
          version: '$(FlutterVersion)'
        

      - script: sudo npm install -g appcenter-cli
      - script: appcenter login --token '$(YOUR_TOKEN)'

      - task: PowerShell@2
        displayName: Setup environment
        inputs:
          targetType: 'inline'
          script: |
            Write-Host "##vso[task.prependpath]$(JAVA_HOME_11_X64)"
            Write-Host "##vso[task.setvariable variable=JAVA_HOME;]$(JAVA_HOME_11_X64)"
            Write-Host "##vso[task.prependpath]$(FlutterToolPath)"
            Write-Host "##vso[task.prependpath]$(FlutterToolPath)/cache/dart-sdk/bin"

      - task: PowerShell@2
        displayName: Setup variables (beta)
        condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/')
        inputs:
          targetType: 'inline'
          script: |
            $buildName = "$(Build.SourceVersion)".SubString(0,7)
            $distributionGroup = "Internal"
            Write-Host "##vso[task.setvariable variable=BuildName;]$buildName"
            Write-Host "##vso[task.setvariable variable=DistributionGroup;]$distributionGroup"

      - task: PowerShell@2
        displayName: Setup variables (public)
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
        inputs:
          targetType: 'inline'
          script: |
            $buildName = "$(Build.SourceBranch)".SubString(11)
            $distributionGroup = "Internal"
            Write-Host "##vso[task.setvariable variable=BuildName;]$buildName"
            Write-Host "##vso[task.setvariable variable=DistributionGroup;]$distributionGroup"

      - task: CmdLine@2
        displayName: Run install
        inputs:
          script: |
           flutter pub get
           cd ios
           pod repo update
           rm Podfile.lock
           rm -rf Pods
           cd ..
      - task: FlutterBuild@0
        displayName: 'Flutter Build ios'
        inputs:
          target: 'ios'
          projectDirectory: '$(ProjectDirectory)'
          buildName: '$(BuildName)'
          buildNumber: '$(BuildNumber)'
          iosCodesign: false
      - task: CopyFiles@2
        inputs:
          contents: '**/*.ipa'
          targetFolder: '$(build.artifactStagingDirectory)'
          overWrite: true
      - task: PublishBuildArtifacts@1
        inputs:
          artifactName: 'drop' 
      - task: AppCenterDistribute@3
        displayName: 'Distribute ipa on app center'
        inputs:
          serverEndpoint: 'AppCenter Service Connection'
          appSlug: '$(ProjectSlug)'
          appFile: '$(BuildDirectoryIos)'
          releaseNotesOption: 'input'
          releaseNotesInput: '$(BuildMessage)'
          destinationType: 'groups'
      - task: FlutterBuild@0
        displayName: 'Flutter Build android'
        inputs:
          target: 'apk'
          projectDirectory: $(projectDirectory)
          buildName: '$(BuildNumber)'  
      - task: CopyFiles@2
        inputs:
          contents: '**/*.apk'
          targetFolder: '$(build.artifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          artifactName: 'drop'
      - task: AppCenterDistribute@3
        displayName: 'Distribute android on app center'
        inputs:
          serverEndpoint: 'AppCenter Service Connection Android'
          appSlug: '$(ProjectSlug)'
          appFile: '$(BuildDirectoryAndroid)'
          releaseNotesOption: 'input'
          releaseNotesInput: 'New version'
          destinationType: 'groups'