name: app
description: Manapipes app.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  validator:
    git: https://github.com/jodinathan/validator.dart
  web_socket_channel: ^1.1.0
  fluro: ^1.6.3
  rxdart: ^0.24.0
  intl: ^0.16.0
  animated_background: ^1.0.5
  tuple: ^1.0.2
  percent_indicator: '^1.0.13'
  dio: ^3.0.3
  flutter_webview_plugin: ^0.3.10+1
  easy_web_view:
      path: ./modules/easy_web_view
  firebase_auth: ^0.15.3
  geolocator: ^5.1.3
  #cached_network_image: 1.1.3
  cached_network_image: ^2.2.0+1
  date_utils: ^0.1.0
  flutter_launcher_icons: ^0.7.2+1
  openapi:
    path: ./openapi
  sticky_headers: '^0.1.8'
  sembast: ^1.13.0
  url_launcher: ^5.4.10
  url_launcher_web: ^0.1.1+6
  google_maps_flutter: ^0.5.26+4
  google_maps: '>=3.0.0 <4.0.0'
  tinycolor: ^1.0.2
  shimmer: ^1.0.1
  date_format: ^1.0.6
  material_design_icons_flutter: ^3.2.3595
  queries: ^0.1.9
  sliver_fab: '^1.0.0'
  font_awesome_flutter: ^8.4.0
  uri: ^0.11.3+1
  google_maps_webservice: ^0.0.15
  firebase_messaging: ^6.0.13
  charts_flutter: ^0.9.0
  flutter_section_table_view: ^1.0.5
  shake: ^0.1.0
  wave: ^0.0.8
  share: ^0.6.1
  achievement_view: ^0.2.0
  avatar_glow: ^1.1.0
  auto_size_text: ^2.1.0
  flushbar: ^1.10.0
  date_range_picker: ^1.0.5
  #flutter_qr_scanner: ^0.1.5
  flutter_material_color_picker: ^1.0.0
  flutter_form_builder: ^3.6.1
  image_picker: ^0.6.1+4
  shared_preferences: 0.5.4+5
  flutter_slidable: '^0.5.3'
  smooth_star_rating: ^1.0.3
  fl_chart: ^0.1.5
  firebase_dynamic_links: ^0.5.0+1
  giffy_dialog: ^1.3.0
  pretty_dio_logger: ^1.0.4
  apple_sign_in: ^0.1.0
  clustering_google_maps:
    git: https://github.com/giandifra/clustering_google_maps.git
  universal_html: ^1.1.8
  #webview_flutter: ^0.3.15+1
  #easy_google_maps: ^1.0.0+2
  intro_slider:
    path: ./modules/flutter-intro-slider
  flare_flutter: ^2.0.1
  #qr_mobile_vision: ^1.0.0+3
  mdns_plugin: ^1.1.4
  logger: ^0.9.1
  #logger_flutter:
  #  git: https://github.com/JEuler/logger_flutter.git
  js: ^0.6.0  
  google_sign_in: ^4.5.1

dependency_overrides:

flutter_icons:
  android: true
  ios: 'Example-Icon'
  image_path: 'assets/icon/icon.png'
  image_path_android: 'assets/icon/icon_android.png'
  image_path_ios: 'assets/icon/icon_ios.png'
  adaptive_icon_background: '#FFFAFAFA'
  adaptive_icon_foreground: 'assets/icon/icon-foreground.png'

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  #flutter_test:
  #  sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/color_wheel.png
    - images/gear/bowls.jpg
    - images/gear/coals.jpg
    - images/gear/hms.jpg
    - images/gear/mygear.jpg
    - images/gear/hookah.jpg
    - images/gear/tobacco.jpg
    - images/stats.png

    - images/devices/white.jpg
    - images/devices/black.jpg
    - images/devices/wood.jpg
    - images/devices/prototype.jpg

    - images/logo.png

    - images/types/bowl.png
    - images/types/coal.png
    - images/types/heatmanagment.png
    - images/types/hookah.png
    - images/types/tobacco.png

    - locale/localization_en.json
    - locale/localization_cs.json
    - locale/localization_de.json

    - assets/

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ManaIcons
      fonts:
        - asset: fonts/Mana-Icons.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
