name: app
description: Manapipes app.
version: 1.0.0+1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  validator:
    git: https://github.com/jodinathan/validator.dart
  web_socket_channel: ^2.1.0
  fluro: ^2.0.3
  rxdart: ^0.27.1
  intl: ^0.17.0
  animated_background: ^2.0.0
  dartz: ^0.10.0
  percent_indicator: ^3.4.0
  dio: ^4.0.0
  #flutter_webview_plugin: ^0.3.11
  firebase_auth: ^1.4.1
  firebase_core: ^1.3.0
  firebase_dynamic_links: ^2.0.6
  firebase_messaging: ^10.0.2
  permission_handler: ^8.2.5
  geolocator: ^7.7.0
  geocoding: ^2.0.1
  #cached_network_image: 1.1.3
  cached_network_image: ^3.0.0
  date_utils: ^0.2.0
  flutter_launcher_icons: ^0.9.0
  openapi:
    path: ./openapi
  sticky_headers: ^0.2.0
  sembast: ^3.1.0+2
  url_launcher: ^6.0.5
  url_launcher_web: ^2.0.1
  google_maps_flutter: ^2.0.6
  google_maps: ^5.1.0
  tinycolor: ^1.0.2
  shimmer: ^2.0.0
  date_format: ^2.0.2
  material_design_icons_flutter: ^4.0.5345
  queries: ^0.1.9
  sliver_fab: '^1.0.0'
  font_awesome_flutter: ^9.1.0
  uri: ^1.0.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  charts_flutter:
    git:
      url: https://github.com/google/charts.git
      path: charts_flutter
  flutter_section_table_view: ^1.0.5
  shake: ^1.0.1
  wave:
    git:
      url: git://github.com/searchy2/wave.git
  share: ^2.0.4
  achievement_view: ^0.2.0
  avatar_glow: ^2.0.1
  auto_size_text: ^2.1.0
  another_flushbar: ^1.10.5
  date_range_picker: 
    git: https://github.com/tcd93/date_range_picker
  qr_code_scanner: ^0.6.1
  flutter_material_color_picker: ^1.0.0
  image_picker: ^0.8.1+1
  shared_preferences: ^2.0.8
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.6
  flutter_slidable: ^0.6.0
  smooth_star_rating: ^1.0.3
  fl_chart: ^0.36.2
  giffy_dialog: ^1.3.0
  pretty_dio_logger: ^1.0.4
  sign_in_with_apple: ^3.2.0
  universal_html: ^2.0.8
  intro_slider:
    path: ./modules/flutter-intro-slider
  flare_flutter: ^2.0.1
  #qr_mobile_vision: ^1.0.0+3
  flutter_mdns_plugin: ^0.0.3
  logger: ^1.0.0

  js: ^0.6.0
  google_sign_in: ^5.1.1
  google_sign_in_web: ^0.10.0+3
  get_it: ^7.2.0
  provider: ^5.0.0
  flutter_chips_input: ^1.9.0-dev.1
  google_fonts: ^2.1.0
  dependencies:
  flutter_facebook_auth: ^3.5.2
  alice: ^0.2.4
  clickable_list_wheel_view: ^0.0.4

dependency_overrides:
  quiver: ^3.0.1
  better_player: 0.0.73
  
  

flutter_icons:
  android: true
  ios: 'Example-Icon'
  image_path: 'assets/icon/icon.png'
  image_path_android: 'assets/icon/icon_android.png'
  image_path_ios: 'assets/icon/icon_ios.png'
  adaptive_icon_background: '#FFFAFAFA'
  adaptive_icon_foreground: 'assets/icon/icon-foreground.png'

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  build_runner:
  #flutter_test:
  #  sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/color_wheel.png
    - images/gear/bowls.jpg
    - images/gear/coals.jpg
    - images/gear/hms.jpg
    - images/gear/mygear.jpg
    - images/gear/hookah.jpg
    - images/gear/tobacco.jpg
    - images/stats.png

    - images/devices/white.jpg
    - images/devices/black.jpg
    - images/devices/wood.jpg
    - images/devices/prototype.jpg

    - images/logo.png

    - images/types/bowl.png
    - images/types/coal.png
    - images/types/heatmanagment.png
    - images/types/hookah.png
    - images/types/tobacco.png

    - locale/localization_en.json
    - locale/localization_cs.json
    - locale/localization_de.json

    - assets/

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ManaIcons
      fonts:
        - asset: fonts/Mana-Icons.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
