name: app
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  validator:
    git: https://github.com/jodinathan/validator.dart
  web_socket_channel: '^1.0.9'
  fluro: '^1.3.7'
  flutter_secure_storage: '^3.1.2'
  rxdart: '^0.19.0'
  vibrate: '^0.0.4'
  intl: ^0.15.6
  animated_background: ^1.0.0
  tuple: ^1.0.1
  percent_indicator: '^1.0.9'
  qrcode_reader: ^0.4.4
  dio: ^1.0.9
  charts_flutter: ^0.4.0
  flutter_sparkline:
    git: https://github.com/xqwzts/flutter_sparkline.git
  flutter_facebook_login: ^1.1.1
  map_view: ^0.0.14
  location: ^1.4.1
  cached_network_image: '^0.4.1'
  date_utils: ^0.1.0
  flutter_launcher_icons: ^0.6.1
  openapi:
    path: ./openapi
  sticky_headers: '^0.1.7'
  # onesignal: ^1.0.3
  sembast: ^1.13.0
  url_launcher: ^4.0.3
  google_maps_flutter: ^0.0.3+3
  tinycolor: ^1.0.2


flutter_icons:
  android: true
  ios: 'Example-Icon'
  image_path: 'assets/icon/icon.png'
  image_path_android: 'assets/icon/icon_android.png'
  image_path_ios: 'assets/icon/icon_ios.png'
  adaptive_icon_background: '#FFFAFAFA'
  adaptive_icon_foreground: 'assets/icon/icon-foreground.png'

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/color_wheel.png
    - images/gear/bowls.jpg
    - images/gear/coals.jpg
    - images/gear/hms.jpg
    - images/gear/mygear.jpg
    - images/gear/hookah.jpg
    - images/gear/tobacco.jpg
    - images/stats.png

    - images/devices/white.jpg
    - images/devices/black.jpg
    - images/devices/wood.jpg
    - images/devices/prototype.jpg

    - images/logo.png

    - locale/localization_en.json
    - locale/localization_cs.json
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ManaIcons
      fonts:
        - asset: fonts/Mana-Icons.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
