name: app
description: Manapipes app.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.2.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  web_socket_channel: ^2.2.0
  fluro: ^2.0.3
  rxdart: ^0.27.5
  intl: ^0.18.0
  animated_background: ^2.0.0
  dartz: ^0.10.1
  percent_indicator: ^4.2.2
  dio: ^4.0.6
  arkit_plugin: 
     path: ./modules/arkit_flutter_plugin
  #flutter_webview_plugin: ^0.3.11
  firebase_core_platform_interface: 4.8.0
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  firebase_dynamic_links: ^5.3.4
  firebase_messaging: ^14.6.5
  permission_handler: ^10.0.0
  geolocator: ^9.0.1
  geocoding: ^2.0.4
  #cached_network_image: 1.1.3
  cached_network_image: ^3.2.1
  date_utils: ^0.2.0
  flutter_launcher_icons: ^0.13.0
  openapi:
    path: ./openapi
  sticky_headers: ^0.3.0+2
  sembast: ^3.2.0+1
  url_launcher: ^6.1.5
  url_launcher_web: ^2.0.13
  google_maps_flutter: ^2.1.10
  google_maps: ^6.2.0
  tinycolor2: ^3.0.1
  shimmer: ^2.0.0
  date_format: ^2.0.6
  material_design_icons_flutter: ^6.0.7096
  font_awesome_flutter: ^10.4.0
  uri: ^1.0.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  shake: ^2.1.0
  wave: ^0.2.2
  share: ^2.0.4
  avatar_glow: ^2.0.2
  auto_size_text: ^3.0.0
  another_flushbar: ^1.10.29
  date_range_picker: 
    git: https://github.com/tcd93/date_range_picker
  qr_code_scanner: ^1.0.0
  flutter_material_color_picker: ^1.1.0+2
  image_picker: ^0.8.5+3
  shared_preferences: ^2.0.15
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  flutter_slidable: ^2.0.0
  smooth_star_rating:
    git: https://github.com/bhavin-concetto/smoothratingbar
  fl_chart: ^0.61.0
  giffy_dialog: 
    git: https://github.com/Simouche/giffy_dialog
  pretty_dio_logger: ^1.2.0-beta-1
  sign_in_with_apple: ^4.1.0
  universal_html: ^2.0.8
  intro_slider:
    path: ./modules/flutter-intro-slider
  flare_flutter:
    git:
      url: https://github.com/tsinis/Flare-Flutter
      path: flare_flutter/ 
  #qr_mobile_vision: ^1.0.0+3
  logger: ^1.1.0
  js: ^0.6.4
  google_sign_in: ^6.1.0
  google_sign_in_web: ^0.12.0
  get_it: ^7.2.0
  provider: ^6.0.3
  flutter_chips_input: ^2.0.0
  google_fonts: ^4.0.3
  flutter_facebook_auth: ^5.0.8
  alice_lightweight: ^3.1.0
  clickable_list_wheel_view: ^0.2.0
  darq: ^1.2.1
  collection: ^1.15.0-nullsafety.4
  flutter_neumorphic: ^3.2.0
  health: ^7.0.1

dependency_overrides:
  flare_flutter:
    git:
      url: https://github.com/tsinis/Flare-Flutter
      path: flare_flutter/
  intl: ^0.18.0
  

flutter_icons:
  android: true
  ios: 'Example-Icon'
  image_path: 'assets/icon/icon.png'
  image_path_android: 'assets/icon/icon_android.png'
  image_path_ios: 'assets/icon/icon_ios.png'
  adaptive_icon_background: '#FFFAFAFA'
  adaptive_icon_foreground: 'assets/icon/icon-foreground.png'

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  build_runner: ^2.2.0

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/color_wheel.png
    - images/gear/bowls.jpg
    - images/gear/coals.jpg
    - images/gear/hms.jpg
    - images/gear/mygear.jpg
    - images/gear/hookah.jpg
    - images/gear/tobacco.jpg
    - images/stats.png
    - images/so_logo.jpg
    - images/devices/white.jpg
    - images/devices/black.jpg
    - images/devices/wood.jpg
    - images/devices/prototype.jpg

    - images/logo.png

    - images/types/bowl.png
    - images/types/coal.png
    - images/types/heatmanagment.png
    - images/types/hookah.png
    - images/types/tobacco.png

    - locale/localization_en.json
    - locale/localization_cs.json
    - locale/localization_de.json

    - assets/

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ManaIcons
      fonts:
        - asset: fonts/Mana-Icons.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
