name: intro_slider
description: Flutter Intro Slider is a flutter plugin that helps you make a cool intro for your app
authors:
  - Duy Tran <tranquangduy7994@gmail.com>
homepage: https://github.com/duytq94/flutter-intro-slider
version: 2.2.8

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"