// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3dZXCM4sdnGZB4x4f5M6nXX-D9Xm-r5w',
    appId: '1:652590711591:web:ce16d1bcf223abfe861f02',
    messagingSenderId: '652590711591',
    projectId: 'manapipes',
    authDomain: 'manapipes.firebaseapp.com',
    databaseURL: 'https://manapipes.firebaseio.com',
    storageBucket: 'manapipes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCImUErdFgyFQsOtYde5XJ67BrO-Ji8YJU',
    appId: '1:652590711591:android:41251d98bc2d08d0',
    messagingSenderId: '652590711591',
    projectId: 'manapipes',
    databaseURL: 'https://manapipes.firebaseio.com',
    storageBucket: 'manapipes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFf-QlaA4717igTKx7Pc_cX_rkqMGUoYY',
    appId: '1:652590711591:ios:c2f74b9b199ba7c0861f02',
    messagingSenderId: '652590711591',
    projectId: 'manapipes',
    databaseURL: 'https://manapipes.firebaseio.com',
    storageBucket: 'manapipes.appspot.com',
    androidClientId: '652590711591-i8t2g5s1ep8bnp7vu4oeijglj9dgul5g.apps.googleusercontent.com',
    iosClientId: '652590711591-fel7h12l3c7erk4do9a4rvpfbhhn9avo.apps.googleusercontent.com',
    iosBundleId: 'com.freyadev.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFf-QlaA4717igTKx7Pc_cX_rkqMGUoYY',
    appId: '1:652590711591:ios:819da73667c9e72e861f02',
    messagingSenderId: '652590711591',
    projectId: 'manapipes',
    databaseURL: 'https://manapipes.firebaseio.com',
    storageBucket: 'manapipes.appspot.com',
    androidClientId: '652590711591-i8t2g5s1ep8bnp7vu4oeijglj9dgul5g.apps.googleusercontent.com',
    iosClientId: '652590711591-bft2j5s4dl9398abg9vl1148h23iujj7.apps.googleusercontent.com',
    iosBundleId: 'com.manapipes.manapipesFlutter',
  );
}
